version: '3.8'
services:
  bot:
    build: .
    env_file:
      - .env
    restart: always

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
