version: '3.8'

services:
  bot:
    build: .
    container_name: sparx-bot
    restart: always                # <- Kluczowe!
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs           # opcjonalnie logi
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"