version: '3.3'

services:
  bot:
    build: .
    container_name: sparx-bot
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
